### PR TITLE
Implements Wikimedia and Scribe Page

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist
-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
- The pull request implements the Wikimedia Scribe page. The page can be accessed from the About page by clicking on the option Wikimedia and Scribe.
### Related issue
-  #52

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋 I've set up a new device at this point and it's telling me that the Gradle settings are out of date, so I can't build the app. Would we be able to upgrade the Gradle settings as a part of this, and then hopefully I'll be able to review?

**Comment by angrezichatterbox** [comment]
> Hey @angrezichatterbox 👋 I've set up a new device at this point and it's telling me that the Gradle settings are out of date, so I can't build the app. Would we be able to upgrade the Gradle settings as a part of this, and then hopefully I'll be able to review?

Ya, I will upgrade the Gradle and push the changes.

**Comment by angrezichatterbox** [comment]
I have updated the Gradle version. I have to upgrade some dependencies along with it. Due to this, I had to make layout changes to the About activity and the Wikimedia Scribe page I had just created.

**Comment by andrewtavis** [comment]
Thanks for all the effort here, @angrezichatterbox! 🏆

**Comment by andrewtavis** [comment]
Will get to the review soon :)

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the quick reaction and update so the review was easier, @angrezichatterbox! Really appreciate it 😊 All is looking wonderful here! Maybe we want to think about bringing in Scribe-i18n soon so that it's easier to get the needed texts for the application? I'll ping you in that issue 😇

**Pull request merged**
