### PR TITLE
App hints

### PR DESCRIPTION
**Pull request by ZayJackPrvy**
### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
I accidentally deleted the previous pull request while trying to resolve an issue. I hope everything is okay.
I i

### Related issue

-   #ISSUE_NUMBER

### CODE REVIEW

**Comment by ZayJackPrvy** [comment]
@andrewtavis I deleted previous pull request while trying to resolve the conflicts in `AboutFragment.kt`

**Comment by andrewtavis** [comment]
All good, @ZayJackPrvy!

**Comment by andrewtavis** [comment]
Can you fix the linting check and then we can bring this in, @ZayJackPrvy? :)

**Comment by ZayJackPrvy** [comment]
@andrewtavis Finally, sorry for that. 😁

**Comment by andrewtavis** [comment]
Sorry to bring something else here, @ZayJackPrvy: Currently the project doesn't build for me on your branch.

Error is:

```
Android resource linking failed
be.scri.app-mergeCoreDebugResources-57:/layout/hint_layout.xml:46: error: resource string/hint_ok_button_text (aka be.scri.debug:string/hint_ok_button_text) not found.
error: failed linking file resources.
```

There's also a lot of commented out code in this PR, so could we reduce that down? Maybe some of that code's what's needed to get the build working again?

**Comment by andrewtavis** [comment]
Is the app building on your end, @ZayJackPrvy?

For me I get:

```
e: file:///Users/andrewtavis/coding/scribe-org/Scribe-Android/app/src/main/java/be/scri/fragments/AboutFragment.kt:225:43 Unresolved reference 'Context'.
```

**Comment by ZayJackPrvy** [comment]
It's not. The issue is that I couldn't resolve the problem directly in Git, so I had to do it locally. Git didn't allow me to merge automatically, so I don't currently have the latest version.

**Comment by andrewtavis** [comment]
Ok, maybe the thing to do then is to create a new branch with a fresh version of main on there, and then reimplement the changes so we can be sure that it'll build?

**Comment by ZayJackPrvy** [comment]
Ok, Now it's working on my site. Sorry for troubles I caused.

**Review by andrewtavis — APPROVED** [review]
No troubles caused, @ZayJackPrvy! Just wanting to make sure that we get this in :) Really appreciate you seeing it through to the end! 😊

**Pull request merged**
