### PR TITLE
107 fix detekt too many functions

### PR DESCRIPTION
**Pull request by growabeard**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR is a WIP attempt to fix the TooManyFunctions detekt metric.

To test, I ran the application locally and attempted to use the app and the keyboard.

Previously it was at 27 issues, and I have reduced that down to 5.

This is a large PR, I understand. Most of the code was unused. Some of it was restructured to add layers of inheritance.

The remaining offenders are 
-MyKeyboardView: 30 functions
-BaseSimpleActivity: 27 functions
-SimpleKeyboardIME: 21 functions
-ContextStorage: 15 functions
-SettingsFragment: 13 functions

I'm not sure if we should add suppression annotations to these classes or if I should proceed and try to whittle this down further.

### Related issue

-   #107

### CODE REVIEW

**Comment by andrewtavis** [comment]
CC @angrezichatterbox for #200 that came out of our discussions :)

**Comment by andrewtavis** [comment]
Let us know when this is ready, @growabeard, and really thanks so much 😊

**Comment by angrezichatterbox** [comment]
I guess this PR would fix most of #200 along with my PR :)

**Comment by growabeard** [comment]
Closing this PR and I will split into multiple more manageable PRs.

**Pull request closed without merging**
