### PR TITLE
feat:Added a shadow beneath the key

### PR DESCRIPTION
**Pull request by angrezichatterbox**

### CODE REVIEW

**Comment by andrewtavis** [comment]
Finally able to test this a bit, @angrezichatterbox :) So generally it's working, but the space bar being made smaller by padding isn't ideal. Ideally we could get these keys looking like the iOS ones with rounding and a bit of space between the keys. Do you think that that would be possible? We can also hold off on the edits until you're done with the research in #34 :)

**Comment by angrezichatterbox** [comment]
Ok I will fix it after I look into the AOSP keyboard and will also look into the other issues ..

**Comment by angrezichatterbox** [comment]
I am free to discuss any changes that is required to be made in this project .

**Comment by andrewtavis** [comment]
Sounds great :) Let's check in maybe once you have some thoughts on #34!

**Comment by angrezichatterbox** [comment]
Sorry for the delay in checking and fixing the issues as well the AOSP thing I had exams I will return to correcting those from tmrw

**Comment by andrewtavis** [comment]
100% ok, @angrezichatterbox! Good luck with exams :)

**Comment by angrezichatterbox** [comment]
I have made some changes to the code and made the keys more rounded also I fixed the issue of space bar having rounded white curbed rectangle in between.

**Review by andrewtavis — APPROVED** [review]
Hey @angrezichatterbox 👋 All's looking really good here! I'll bring this in and write in the issue about the next steps :)

**Pull request merged**
