### PR TITLE
Style first autosuggestion button based on the gender of a word typed 

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR implements Gender | Plural auto suggestion for each word we type. This could be seen while typing a word and the first auto suggest button changes to the gender | PL for plural. 

### Related issue

-   #135

### CODE REVIEW

**Comment by andrewtavis** [comment]
Amazing to see this, @angrezichatterbox! 🚀🚀🚀 This was the very first functionality of Scribe-iOS, and it's finally coming to Android 😊

A couple comments here:
- The annotation should only be shown after the user presses space
- We have the underlined annotations that are shown under autocompletions and suggestions as words are being typed, but the actual annotation should only be after space is pressed
- Can we get the annotation to be styled a bit more
    - I think the autosuggestion buttons need a bit more space between them - say each is 90% their current width, which will then translate to the annotation button
    - Can we get the corners to be a bit rounded
    - For now we don't need a shadow, but for preposition annotation we will need it, FYI (and eventually for this)
- And here are the colors:
    - `annotateRed`: Light #9F1722; Dark #FB5F6C
    - `annotateBlue`: Light #335C99; Dark #339EEB
    - `annotatePurple`: Light #700589; Dark #AC6DEC
    - `annotateGreen`: Light #3D7946; Dark #85C26F
    - `annotateOrange`: Light #F85A39; Dark #FD9F5D
    - Can you name them as the above as well so we're consistent across the apps?

Let me know if there are any questions on the above!

**Comment by andrewtavis** [comment]
Looking forward, @angrezichatterbox!

**Comment by andrewtavis** [comment]
Let me know when this is ready for a final review, @angrezichatterbox 😊

**Comment by angrezichatterbox** [comment]
It is ready for review 😄

**Comment by andrewtavis** [comment]
Nice! Will check it tonight or tomorrow :)

**Review by andrewtavis — APPROVED** [review]
Really such a pleasure to bring this in, @angrezichatterbox 😊 Thanks so much for your dedication to the project :) :)

Minor changes will likely come in the future like making the characters of the annotations a bit larger than the autosuggestions, but this is all fine tuning that we can get to when we have some more progress and can start checking the Android app in direct comparison to the iOS one. Can't wait!

**Pull request merged**
