### PR TITLE
Add license tag to all Kotlin files (#282)

### PR DESCRIPTION
**Pull request by mat-in**
### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

-   #ISSUE_NUMBER

### CODE REVIEW

**Comment by mat-in** [comment]
Added license tags to all .kt files using bash

**Comment by andrewtavis** [comment]
Hey @mat-in 👋 Looks like you might have ran your script multiple times. Can we only have the GPL as it is in the `.swift` file in the issue? Beyond that, it'd be great if we got a short description of what's in the file as the first line of the doc string as is in the `.swift` file. Would you be able to add those as well?

**Comment by mat-in** [comment]
```
/**
 *{ Description}
 *
 * Copyright (C) 2024 Scribe
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
```
Hello! @andrewtavis 
is this the format?

**Comment by andrewtavis** [comment]
Exactly that, @mat-in :) Feel free to open a new PR or re-open this one with the changes!

**Pull request closed without merging**
