### PR TITLE
Migrate wikimedia, privacy policy, and third party licenses screens to compose

### PR DESCRIPTION
**Pull request by growabeard**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description

This is migrating from the xml based layout to Jetpack Compose for the Privacy Policy, Third-party licenses, and Wikimedia screens.

I have tested on my personal device by changing from light mode to dark mode and scrolling up and down on the device.

privacy_dark (Small)
privacy_light (Small)

third_party_dark (Small)
third_party_light (Small)

wikimedia_dark (Small)
wikimedia_light (Small)

### Related issue

-   #217

### CODE REVIEW

**Comment by andrewtavis** [comment]
This is great, @growabeard! Amazing to have the conversion for all of these done 😊 From the usability standpoint the only thing I'm seeing is that it'd be good to have a bit of padding at the bottom of the cards in case they do need to scroll, as as of now the bottom of the page looks a bit off as the card touches the tab bar directly :)

Screenshot 2024-12-03 at 08 58 02

@angrezichatterbox, would be great to get a review from you as well here! :)

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, would be great to get a review from you as well here! :)

I'll review it later today evening :)

**Comment by growabeard** [comment]
> This is great, @growabeard! Amazing to have the conversion for all of these done 😊 From the usability standpoint the only thing I'm seeing is that it'd be good to have a bit of padding at the bottom of the cards in case they do need to scroll, as as of now the bottom of the page looks a bit off as the card touches the tab bar directly :)
> 
> Screenshot 2024-12-03 at 08 58 02
> 
> @angrezichatterbox, would be great to get a review from you as well here! :)

Yeah for sure, something like an extra 5 or 10 padding to the spacer should help with that.

Good suggestion, thanks!

**Comment by growabeard** [comment]
This is ready for review, I just added one last change to address @andrewtavis comment.

**Comment by angrezichatterbox** [comment]
After this PR is merged and the about page is converted to Compose. We would have to fix the back swipe in each of the sub pages its currently broken and goes to the previous page in the view pager. This could be either looked as a separate issue or the issue that is to look into pager where navigation would be setup.

**Review by andrewtavis — APPROVED** [review]
Updated changes look great to me, @growabeard 😊 Thanks for getting to the commit so quickly!

**Comment by andrewtavis** [comment]
I think that we have the approvals here, @angrezichatterbox, so let's bring this in :) Can you make an issue for reworking the pagination and ping @growabeard and I in there? Appreciate the care that everyone's putting into the work here! The app's really coming along 😊

**Comment by andrewtavis** [comment]
Or ya I also agree that a new issue isn't necessary and we could do the work to restore navigation in #256. Let us know if you have interest in looking into that, @growabeard!

**Pull request merged**
