### PR TITLE
feat:Implemented Install Keyboard Page

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

### Description

The PR implements the Install Keyboards for the settings page during the first install for the user. On Selection of the keyboard language select language settings for the individual settings shows up. 

### Related issue

-   #119

### CODE REVIEW

**Comment by andrewtavis** [comment]
Quick notes on this PR, @angrezichatterbox:

- Is it possible to remove the message forcing users to install a keyboard?
    - So I mean "Thanks for downloading Scribe! Please enable keyboards on the next screen and press 'Back' when finished."
- The install keyboards button on `Settings` when a keyboard isn't installed isn't showing up in dark mode

We'll be ready to merge after both of these! Thanks for the efforts so far!

**Comment by angrezichatterbox** [comment]
> Quick notes on this PR, @angrezichatterbox:
> 
> * Is it possible to remove the message forcing users to install a keyboard?
>   
>   * So I mean "Thanks for downloading Scribe! Please enable keyboards on the next screen and press 'Back' when finished."
> * The install keyboards button on `Settings` when a keyboard isn't installed isn't showing up in dark mode
> 
> We'll be ready to merge after both of these! Thanks for the efforts so far!

I will remove the message forcing users to install the keyboard. As for the install keyboards button not showing in the dark mode I’m not entirely certain about that issue. For me, the button is visible in dark mode. Could you clarify if you meant something different? Thank you!

Screenshot 2024-10-02 at 9 42 02 AM

**Comment by angrezichatterbox** [comment]
I have added the changes to make the Install keyboard text not be in all caps and removed new users being forced to install the keyboards.

**Review by andrewtavis — APPROVED** [review]
All working wonderfully, @angrezichatterbox! Thanks for this :) :) Nice to have the initial interactions of the user a bit more set 😊

**Pull request merged**
