### PR TITLE
Refactor RecyclerView item decoration in AboutFragment and SettingsFr…

### LINKED ISSUE #139: Add in the small divider line between About options and Settings options without a description
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In Scribe-iOS there is a small line that separates the different items in the Table View when there is no description. This can be seen in the image given below.

Screenshot 2024-09-22 at 10 54 54 AM

Currently, Scribe-Android does not separate the items in the Recycler View using a line when there is no description. This issue aims to add a line between items in a recycler view when there is no description. 

Screenshot 2024-09-22 at 10 56 36 AM

### Contribution

I would love to work on this and am more than willing to help anyone fix this issue :)

### PR DESCRIPTION
**Pull request by MostafaMohamed2002**
…agment

- Extracted the custom RecyclerView item decoration logic into a separate class called CustomDividerItemDecoration.
- Added the CustomDividerItemDecoration to the RecyclerViews in AboutFragment and SettingsFragment.
- Applied a custom drawable as the divider with a width of 1dp and rounded corners.
- Set the left and right margins of the dividers to 50dp.

Fixes #139

### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

#139

### CODE REVIEW

**Comment by MostafaMohamed2002** [comment]
do i have a permission to resolve conflicts ?

**Comment by andrewtavis** [comment]
Another quick thing here, @MostafaMohamed2002: On a Pixel 8 Pro emulator the lines between the languages in settings seem to be button outlines:

Screenshot 2024-10-12 at 16 29 05

Could we get that to just be an individual line and not having the sides as well?

**Comment by MostafaMohamed2002** [comment]
I'll check on it and fix it 😃

**Comment by andrewtavis** [comment]
Thanks, @MostafaMohamed2002!

**Comment by MostafaMohamed2002** [comment]
Screenshot_1728832321

**Comment by andrewtavis** [comment]
Nice, looking great! Do you want to fix the merge conflict and I'll bring it in? :)

**Comment by MostafaMohamed2002** [comment]
thanks , but i need to take alook at language settings fragment 😊
soon i'll ask for merge .

**Comment by MostafaMohamed2002** [comment]
it's ready to merge , you can have a final look if it's necessary 😊

**Comment by MostafaMohamed2002** [comment]
when resolving the conflict i should choose the right and left side , i accepted the left only 😂

**Comment by andrewtavis** [comment]
So i should add `import CustomDividerItemDecoration`, @MostafaMohamed2002?

**Comment by MostafaMohamed2002** [comment]
> So i should add `import CustomDividerItemDecoration`, @MostafaMohamed2002?

No it's all ok now 👌

**Review by andrewtavis — APPROVED** [review]
Looking great, @MostafaMohamed2002! 😊 Really appreciate your continued support for the project 🚀

**Pull request merged**
