### PR TITLE
Implement disable and enable of  accent characters

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- The pull request allows disabling and enabling accent characters in the German, Swedish, and Spanish keyboards. By default they are enabled. 

### Related issue

-   #67 
-   #65

### CODE REVIEW

**Comment by angrezichatterbox** [comment]
There are some additional changes to be made to the PR.

**Comment by angrezichatterbox** [comment]
It is ready for review now.

**Comment by andrewtavis** [comment]
Can you do a quick fix of the conflicts and then I'll do a final review for this tonight, @angrezichatterbox? :) Or whenever you have time 😊

**Comment by angrezichatterbox** [comment]
> Can you do a quick fix of the conflicts and then I'll do a final review for this tonight, @angrezichatterbox? :) Or whenever you have time 😊

I will do it by tonight.

**Comment by angrezichatterbox** [comment]
It is ready for review :) .

**Review by andrewtavis — APPROVED** [review]
Wonderful work as always, @angrezichatterbox 😊 Thanks so much for the implementation here!

What are your thoughts on the toasts? You have one for enabling and disabling these options, which isn't something that's currently in Scribe-iOS. Do you think that having these would be important to include in Scribe-iOS, or would it make sense to remove these in another commit at some point?

**Comment by angrezichatterbox** [comment]
> Wonderful work as always, @angrezichatterbox 😊 Thanks so much for the implementation here!
> 
> What are your thoughts on the toasts? You have one for enabling and disabling these options, which isn't something that's currently in Scribe-iOS. Do you think that having these would be important to include in Scribe-iOS, or would it make sense to remove these in another commit at some point?

I think the Switch Item effectively conveys its purpose on its own. Its visual design, along with the text and description, makes it easily identifiable. It might be worth considering whether the Toast adds any additional value. I’d love to hear your opinion about it.

**Pull request merged**
