### PR TITLE
Add license tag and description to Kotlin files

### PR DESCRIPTION
**Pull request by mat-in**
### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

-   #ISSUE_NUMBER

### CODE REVIEW

**Comment by mat-in** [comment]
Hello! @andrewtavis is it sorted?

**Comment by andrewtavis** [comment]
I'll take a look soon, @mat-in! Thanks for it!

**Comment by mat-in** [comment]
Sure, no problem😊 @andrewtavis

**Review by andrewtavis — APPROVED** [review]
Thanks much for the contribution here, @mat-in! Really appreciate the efforts for a great first contribution 😊

**Comment by mat-in** [comment]
No problem 😊 @andrewtavis i hope to contribute more!

**Pull request merged**
