### PR TITLE
Migrated about page from XML to Jetpack Compose

### PR DESCRIPTION
**Pull request by Saifuddin53**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description

The pull request moves the about page to Jetpack Compose

### Screenshots

| Before | After |
|---|---|
| Before | WhatsApp Image 2024-12-06 at 10 55 20_ea973503

### Related issue

-   #248

### CODE REVIEW

**Review by angrezichatterbox — APPROVED** [review]
Awesome work @Saifuddin53. All the changes look good to me :)

**Comment by Saifuddin53** [comment]
Thanks for the review @angrezichatterbox ☺️

**Comment by andrewtavis** [comment]
@angrezichatterbox, do you want to bring this one in? 😊

**Comment by andrewtavis** [comment]
Changes look good to me as well and all's functions wonderfully :)

**Comment by andrewtavis** [comment]
I can also merge later this evening after work, but if you do want to merge, @angrezichatterbox, then also remember to close this issue as well 🚀

**Comment by angrezichatterbox** [comment]
> I can also merge later this evening after work, but if you do want to merge, @angrezichatterbox, then also remember to close this issue as well 🚀

I’ll bring this one in and close the issue as well :)

**Pull request merged**
