### PR TITLE
feat: Add Jacoco coverage and report generation

### PR DESCRIPTION
**Pull request by albendz**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [N/A] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)
- [x] I have tested my code (see test notes below)

---

### Description

This change adds the Jacoco plugin to the app/gradle.build.kts file with configuration to generate coverage reports.

Additionally, this adds a step to the unit test Github workflow to use the generated coverage XML to create a comment on PRs. This is not configured to fail the PR build. Details: https://github.com/marketplace/actions/jacoco-report

One thing I wasn't able to configure is coverage verification checks and build time.

I followed details provided in this Medium article on adding coverage to Android projects:  https://medium.com/@nachare.reena8/measure-your-codes-reach-integrating-jacoco-code-coverage-in-android-apps-with-kotlin-dsl-382d577864e7

#### Testing

`./gradlew tasks` output:

```
Reporting tasks
---------------
jacocoCoreDebugCodeCoverage - Generate Jacoco coverage reports for the CoreDebug build
jacocoCoreReleaseCodeCoverage - Generate Jacoco coverage reports for the CoreRelease build
jacocoFdroidDebugCodeCoverage - Generate Jacoco coverage reports for the FdroidDebug build
jacocoFdroidReleaseCodeCoverage - Generate Jacoco coverage reports for the FdroidRelease build
```

Verified `./gradlew jacocoCoreDebugCodeCoverage` generates files with expected content:
* build/reports/jacoco/jacocoCoreDebugCodeCoverage/jacocoCoreDebugCodeCoverage.xml
* build/reports/jacoco/jacocoCoreDebugCodeCoverage/html/index.html

The github action/workflow fails to post a comment to the PR when run. I'm not sure what's causing that. I've enabled debug logging on the action/workflow but someone with repo management permissions may need to help me understand what's going wrong with the token permissions.

### Related issue

-   #196

### CODE REVIEW

**Comment by MahmoudMabrok** [comment]
I think coverage reports not added to pr 
https://github.com/scribe-org/Scribe-Android/actions/runs/11618292715/job/32355382459?pr=227#step:5:182 

I think we might need an action to write results here.

**Comment by albendz** [comment]
> I think coverage reports not added to pr https://github.com/scribe-org/Scribe-Android/actions/runs/11618292715/job/32355382459?pr=227#step:5:182
> 
> I think we might need an action to write results here.

From what I can tell from the logs, the action is trying to write a comment to the PR and getting access denied. I think the default token has the right permissions based on what the other workflows in this repo are doing. When you say we might need an action to write results here, what do you mean? The step I'm adding is the action to write results here though I might be missing a step.

**Comment by MahmoudMabrok** [comment]
if coverage is added to PR, it is supposed to have it as comment on current PR.

**Comment by andrewtavis** [comment]
Yes I guess getting the coverage report as a comment to the PR would be nice :) I've experienced this with CodeCov in the past. Do you have a suggestion on how we could change it to add it in, @MahmoudMabrok?

**Comment by MahmoudMabrok** [comment]
I was to try on a fork and make it run, once finish I will share here.

**Review by andrewtavis — APPROVED** [review]
All looks good to me as far as functionality and output in the workflow 😊 Thanks for getting us up and running here, @albendz!

**Comment by andrewtavis** [comment]
Please let us know if you have some ideas on the PR comment, @MahmoudMabrok :) Really appreciate your interest in the project and wanting to help out!

**Pull request merged**
