### PR TITLE
Growabeard fix darkmode coloration

### PR DESCRIPTION
**Pull request by growabeard**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR fixes dark mode coloring for the main screen button as well as corner polygons on a few screens according to the [figma design](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=581-1539&t=wP5sMYaHXkKslhGE-4).

Apologies apparently the color coming across is not what I see in the app running on my phone.. It's the same as figma I assure you.
scribe_privacy_policy
scribe_licenses
scribe_wikipedia
scribe_main

### Related issue

-   #164

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for the PR, @growabeard!

**Comment by andrewtavis** [comment]
We'll get to the review as soon as we can :)

**Review by angrezichatterbox — APPROVED** [review]
@growabeard 
The changes are looking perfect. Thank you so much for the PR. Hope we will see you make more such contributions to Scribe-Android :)

**Comment by growabeard** [comment]
> @growabeard The changes are looking perfect. Thank you so much for the PR. Hope we will see you make more such contributions to Scribe-Android :). Also, the additional changes like switching from Androidx to material UI card view are very helpful Thanks :)

@angrezichatterbox Appreciate the review! Is there any interest in moving to Jetpack Compose for screens?

**Review by andrewtavis — APPROVED** [review]
I reiterate @angrezichatterbox's sentiments, @growabeard :) Thanks so much for the great contribution, and hope to have more from you in the future 😊

**Pull request merged**
