### PR TITLE
fix:Corrected the keyboard color and keys colors based on condtions

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- The pull request corrects the color of the toolbar and command icons and accordingly changes the color of the enter key when in other modes except idle mode. 

### Related issue

-   #121

### CODE REVIEW

**Comment by angrezichatterbox** [comment]
I’m happy to make any necessary changes to enhance the PR. There may be aspects I’ve missed or misunderstood.

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox! Really great work! The only comments are:

- The enter key should also be special key color like delete, ABC and shift when it's not Scribe blue - right now it's white
- Can we get "suggestion", "suggestion", "suggestion" as the texts on the command keys when they're in the idle mode and we don't have them as "Translate", "Conjugate" and "Plural"

Thanks so much for all the efforts here! Is really paying off :) I'll upload two images to the readme after the above changes. One will be the base keyboard view with suggestions, and the other will be of it with the command keys showing 😊

**Comment by angrezichatterbox** [comment]
> Hey @angrezichatterbox! Really great work! The only comments are:
> 
> * The enter key should also be special key color like delete, ABC and shift when it's not Scribe blue - right now it's white
> * Can we get "suggestion", "suggestion", "suggestion" as the texts on the command keys when they're in the idle mode and we don't have them as "Translate", "Conjugate" and "Plural"
> 
> Thanks so much for all the efforts here! Is really paying off :) I'll upload two images to the readme after the above changes. One will be the base keyboard view with suggestions, and the other will be of it with the command keys showing 😊

I will make these changes to the PR and send the updated PR tomorrow.

**Comment by andrewtavis** [comment]
Thanks, @angrezichatterbox! 😊

**Comment by angrezichatterbox** [comment]
I have made the changes to the PR :)

**Review by andrewtavis — APPROVED** [review]
Amazing work, @angrezichatterbox! Really appreciate the quick updates to some already great updates! 😊 Will merge this in and then update the repo with the new images 🚀

**Pull request merged**
