### PR TITLE
Feat: Add unit testing dependencies

### PR DESCRIPTION
**Pull request by albendz**
Add Junit 5 and Mockk test dependencies with simple test

### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This change adds dependencies to enable writing unit tests including JUnit 5, a dependency to support use of JUnit 5 for android tests, and MockK following details and discussion from #181 

I added a simple test for a utility class as an example.

I ran the following commands to test:
* `./gradlew test`
* `./gradlew check`

For each of these, I verified they fail when expected (set assertions to be incorrect) and pass otherwise.

Once this change is merged, there are a few follow ups needed - I can create issues for these so they can be done later:
* Test code conventions (naming, organization, etc.)
* Adding tests to automated PR checks
* Adding code coverage tooling and automated PR code coverage checks
* Adding example tests with mocking

### Related issue

-   #181

### CODE REVIEW

**Review by angrezichatterbox — APPROVED** [review]
Thanks for the PR @albendz. Everything looks good to me :)

**Review by andrewtavis — APPROVED** [review]
Thanks for this, @albendz! Really great to have the testing setup for Scribe-Android progressing so early on in its life 😊 Would be great if you could make the issues you discussed in the commit message!

**Comment by albendz** [comment]
Thank you! I've created the following issues for next steps:
 #194 
#195 
#196 
#197

**Comment by andrewtavis** [comment]
Thanks so much, @albendz! Really amazing 😊

**Pull request merged**
