### PR TITLE
fix:Linting issues due to generic exception statements

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

The pull request removes Generic exception statements and replaces it with proper exceptions being caught. I have also removed certain functions which are not longer used in the application. I have also removed the dialogs which already existed in the application as it was no longer being used by the application. 

### Related issue

-   #129

### CODE REVIEW

**Comment by angrezichatterbox** [comment]
I will be fixing this in a while. For some reason, it shows me line 224 has a detekt issue but ./gradlew detekt build successfully in my machine.

**Comment by andrewtavis** [comment]
Let me know when this is ready, @angrezichatterbox :)

**Comment by angrezichatterbox** [comment]
It is ready for review :)

**Review by andrewtavis — APPROVED** [review]
Really great work here, @angrezichatterbox :) So grateful to have the improved errors, and thanks so much for getting rid of so much of this unused code! Lots of progress with this one 😊

**Pull request merged**
