### PR TITLE
Remove settings cog

### PR DESCRIPTION
**Pull request by Linfye**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR removed settings cog and extended out the command bar. And I deleted some lines about the cog button in the kotlin scripts.
### Related issue

-   #55

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for this, @Linfye! We'll get to the review soon :)

**Review by angrezichatterbox — COMMENTED** [review]
The PR looks good. However the settings cog has not been removed for the landscape keyboard. Could u remove that and it would be all good.

**Comment by Linfye** [comment]
Sorry I didn't notice this. Now it should be OK.

**Comment by angrezichatterbox** [comment]
> Sorry I didn't notice this. Now it should be OK.

No worries, The PR looks good now. :)

**Review by andrewtavis — APPROVED** [review]
Appreciate the quick work here, @Linfye! Thanks so much for your help! 🚀 Also thanks for the initial review, @angrezichatterbox!

**Pull request merged**
