### PR TITLE
Basic UI for command key functionality

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- The PR adds functionality for changing the UI of the toolbar of the keyboard for different states. Currently, it has idle state select command state, Translate, conjugate and plural states being used. 

### Related issue

-   #89

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋 I've added auto-fixing the linting errors as a topic for the next dev sync :) Historically I haven't done this on projects as I'd like to fix them and learn what the problems were, and we should set up an auto formatting workflow for contributors where the code as formatted correctly on save. Do we want to make an issue for Android Studio settings and then add them to the documentation?

And there are no strings for the commands as those have historically been hard coded into the files themselves. This can also be discussed in the sync!

I'll get to the review this evening :)

**Comment by angrezichatterbox** [comment]
> Hey @angrezichatterbox 👋 I've added auto-fixing the linting errors as a topic for the next dev sync :) Historically I haven't done this on projects as I'd like to fix them and learn what the problems were, and we should set up an auto formatting workflow for contributors where the code is formatted correctly on save. Do we want to make an issue for Android Studio settings and then add them to the documentation?
> 
> And there are no strings for the commands as those have historically been hard coded into the files themselves. This can also be discussed in the sync! Localization just wasn't a thing at the start :)
> 
> I'll get to the review this evening :)

Since we have already set up ktlint, we could do basic formatting of lines or unnecessary spaces using ktlint itself so that at least some of the possible linting issues can be removed when the build is done. It just came across my mind since it's already registered in our gradle tasks while adding ktlint. 

For now, I have hardcoded them as a single language across all the keyboards.

**Comment by angrezichatterbox** [comment]
> > Hey @angrezichatterbox 👋 I've added auto-fixing the linting errors as a topic for the next dev sync :) Historically I haven't done this on projects as I'd like to fix them and learn what the problems were, and we should set up an auto formatting workflow for contributors where the code is formatted correctly on save. Do we want to make an issue for Android Studio settings and then add them to the documentation?
> > And there are no strings for the commands as those have historically been hard coded into the files themselves. This can also be discussed in the sync! Localization just wasn't a thing at the start :)
> > I'll get to the review this evening :)
> 
> Since we have already set up ktlint, we could do basic formatting of lines or unnecessary spaces using ktlint itself so that at least some of the possible linting issues can be removed when the build is done. It just came across my mind since it's already registered in our gradle tasks while adding ktlint. I could add auto formating on save. 
> 
> For now, I have hardcoded them as a single language across all the keyboards.

**Review by andrewtavis — APPROVED** [review]
This is amazing, @angrezichatterbox! First major update to the keyboard 😊 Thanks so much for the continued work here :) We're making so much progress!

**Pull request merged**
