### PR TITLE
Add Installation Instructions 

### PR DESCRIPTION
**Pull request by Linfye**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
The current page looks like this:
image
And I have 3 questions:

1. Are there any click events that need to be added to this page? Currently, my PR has turned this page into a static page.
2. Currently, there is a 'Scribe' title in the top-left corner of the page, which is not present in the Figma design. I'm not sure how to remove it, could you give me some tips?
3. In the Figma design, "Open Scribe Settings" has an underline, and I don't know how to add it in the XML file. Could you help me with that?

Thanks. :)

### Related issue

-   #113

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @Linfye! This is looking amazing 🤩 Really can't wait to bring this in as the app menu will then be at a great point :)

A couple comments on some things that need to change before we merge:

The texts for the field should be:

- `app.installation.keyboard.keyboard_settings`
- `app.installation.keyboard.text_2` (we don't need test_1 for Android)
- `app.installation.keyboard.text_3`

So the final text should be:

```
1. Open keyboard settings
2. Activate keyboards that you want to use
3. When typing, press [KEYBOARD_ICON] to select keyboards
``` 

Specifically we don't want 🌐, but rather ⌨️ and the icon that's used on Android for switching keyboard input methods. On iOS we have the globe for this, but for Android there's a keyboard icon.

Answers to your questions:

1. Are there any click events that need to be added to this page? Currently, my PR has turned this page into a static page.

    - I think all's fine. We can add some toasts for the various buttons, but aside from that all's fine :)

3. Currently, there is a 'Scribe' title in the top-left corner of the page, which is not present in the Figma design. I'm not sure how to remove it, could you give me some tips?

    - @angrezichatterbox, do you have an idea on this?

4. In the Figma design, "Open Scribe Settings" has an underline, and I don't know how to add it in the XML file. Could you help me with that?

    - I'm not too sure on this, but let's not worry about it too much as the XML file will be changing in the comings months when we start converting the app layouts to jetpack compose. No need to worry for now :)

**Comment by angrezichatterbox** [comment]
> > 3\. Currently, there is a 'Scribe' title in the top-left corner of the page, which is not present in the Figma design. I'm not sure how to remove it, could you give me some tips?
> 
> * @angrezichatterbox, do you have an idea on this?

A possible solution would be to hide the action bar on Creation of the MainActivity using supportActionBar.hide() and view pager changes would show the action bar and hide according to which page the user would be. There might be additional changes to be made but this could work.

**Comment by Linfye** [comment]
Thank you for your responses. I have made the changes. Could you review it again? 😊

**Comment by andrewtavis** [comment]
Sorry to ask for two final changes, @Linfye :)

We also want the keyboard installation field to be a button, which is why `Open keyboard settings` is blue and eventually underlined. Could you add an action to that field such that when you press it it opens the list of keyboards to install? So when we click anywhere on the keyboard installation instructions we should go to this page of the settings:

Screenshot_20240923_081747

And the last thing - also sorry for not being clear with this - can we get the ⌨️ changed to the icon that Android uses for switching keyboard inputs? Specifically the one below:

Screenshot 2024-09-23 at 08 18 41

Really is looking great! 😊 So nice to see Scribe-Android like this finally :)

**Comment by Linfye** [comment]
I've made those changes you mentioned. You can review again now. Thanks. 😊

**Comment by angrezichatterbox** [comment]
@Linfye Could u show the action bar in case of the other pages using supportActionBar?.show() command when the view pager changes it position. If it causes adjustment issues in case of nav bar changing position you could try modifying the xml layout of main activity to fill system window.

**Comment by Linfye** [comment]
@angrezichatterbox, I'm not quite clear about what you mean. Are you suggesting to turn on the supportActionBar on the fragment_main.xml? Could you explain in detail how to do it? 😊

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, I'm not quite clear about what you mean. Are you suggesting to turn on the supportActionBar on the fragment_main.xml? Could you explain in detail how to do it? 😊

Sorry I could have been more clear. 

So currently you have hidden the supportActionBar on the MainFragment. The action bar is not visible for the other pages as well. A possible fix for this would be to hide the support Action bar onCreate in the MainActivity. 

and then in the Main Activity in the view pager show the action bar for the other pages. 

https://github.com/scribe-org/Scribe-Android/blob/b1260afe6136a37c49caec534538d97e8617f0b7/app/src/main/java/be/scri/activities/MainActivity.kt#L84-L114

This might  cause the nav bar something to move up and down as the action bar is being changed continuously a possible fix for this would be to fill in window size for the relative layout of the main activity and then accordingly set the background color as well.

**Comment by Linfye** [comment]
I tried several methods, but the action bar always has a strange up and down issue. In the end, I changed the layout of the Installation page and removed the title "Scribe" from the strings.xml characters. Currently, the page looks like this.

image

And action bar from other pages can display as expected.

**Comment by Linfye** [comment]
> I'll let @angrezichatterbox speak to the action bar, @Linfye :) For the icon I was hoping that Android had a pre-built one we could use, but it looks like there's not one. I went ahead and made it :) Can you use the SVGs I'm attaching for light mode and dark mode?
> 
> android_keyboard_icon_dark android_keyboard_icon_light
> 
> Thanks so much!

OK, done. Thanks for the images! 😊

**Comment by andrewtavis** [comment]
Let us know what the final review on your end is, @angrezichatterbox!

**Review by angrezichatterbox — APPROVED** [review]
The PR looks awesome @Linfye. The action bar works fine and is present for all pages.

**Comment by andrewtavis** [comment]
Will play around with it a bit more after work and send along the final review, @Linfye! Thanks :)

**Review by andrewtavis — APPROVED** [review]
All's looking really good, @Linfye! I'll bring this in and note a few more things that need to be done in a new issue 😊 So awesome to see Scribe-Android like this :D

**Pull request merged**
