### PR TITLE
Fix crash on ContributorsActivity, resolve #29

### LINKED ISSUE #29: Crash when starting ContributorsActivity
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

When clicking Contributors button on AboutActivity, the app crashed with this following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.scribe.debug, PID: 3658
    android.content.ActivityNotFoundException: Unable to find explicit activity class {org.scribe.debug/org.scribe.commons.activities.ContributorsActivity}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2256)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1914)
        at android.app.Activity.startActivityForResult(Activity.java:5326)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
        at android.app.Activity.startActivityForResult(Activity.java:5284)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
        at android.app.Activity.startActivity(Activity.java:5670)
        at android.app.Activity.startActivity(Activity.java:5623)
        at org.scribe.commons.activities.AboutActivity.setupContributors$lambda-10(AboutActivity.kt:202)
        at org.scribe.commons.activities.AboutActivity.$r8$lambda$sGzhmgoYzkb0ISNY_Q2TUw7oAWQ(Unknown Source:0)
        at org.scribe.commons.activities.AboutActivity$$ExternalSyntheticLambda6.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7520)
        at android.view.View.performClickInternal(View.java:7489)
        at android.view.View.access$3600(View.java:826)
        at android.view.View$PerformClick.run(View.java:28555)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8030)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
```

### Device type

iPhone

### iOS version

_No response_

### PR DESCRIPTION
**Pull request by sunyiming**

### CODE REVIEW

**Review by andrewtavis — APPROVED** [review]
Works like a charm! I likely deleted this on accident as I was trying to remove unneeded code.

**Comment by andrewtavis** [comment]
@sunyiming, let me know if you have any suggestions for this project or if you have interest in working on other features. Really would be great to get a bit of help with the conversion, and most of what's in the foreseeable future is more busy work and not particularly hard.

Generally the plan is that I'll get to #22 soon that that all the files that are in here are what we'll need, then going to #24 and #21. From there I'd like to start adding the Scribe UI functionality by first finishing #16 :)

Thanks again!

**Comment by sunyiming** [comment]
@andrewtavis Hi! This is a really cool project. Since it is currently in WIP status, I am very happy to contribute to it to make it works. However, I'm just a beginner of Android development, so it will take me some time to learn the project structure before working on it. 

Thanks for merging this patch!

**Comment by andrewtavis** [comment]
@sunyiming, I’m honestly also an Android beginner :) Best way to learn is to build something 😊 Your contributions are very welcome, and feel free to reach out if you have questions!

**Comment by andrewtavis** [comment]
Hello again, @sunyiming :) Just wanted to check in with you on whether you'd like to connect about what's needed for the Android app moving forward. There are a few others who are interested, and I was thinking of doing a call to discuss?

**Pull request merged**
