### PR TITLE
feat:Added Shadow to the keys and reduced border radius 

### PR DESCRIPTION
**Pull request by angrezichatterbox**
The pull request is to make the keyboard similar to the iOS Scribe-App by adding white key and a small shadow below the keys

### CODE REVIEW

**Comment by andrewtavis** [comment]
I'm getting some errors in trying to build this, @angrezichatterbox :)

```
e: .../Scribe-Android/app/src/main/kotlin/org/scribe/services/SimpleKeyboardIME.kt: (45, 5): 'hasTextBeforeCursor' overrides nothing
e: .../Scribe-Android/app/src/main/kotlin/org/scribe/services/SimpleKeyboardIME.kt: (56, 5): 'commitPeriodAfterSpace' overrides nothing
```

Do you want to take a look at them? I'll get the PR template up now :)

**Comment by andrewtavis** [comment]
PR template is [here](https://github.com/scribe-org/Scribe-Android/blob/main/.github/PULL_REQUEST_TEMPLATE.md), and you'll see the raw text in your next PR, @angrezichatterbox. Let me know if you have any suggestions for the template!

**Comment by angrezichatterbox** [comment]
> I'm getting some errors in trying to build this, @angrezichatterbox :)
> 
> ```
> e: .../Scribe-Android/app/src/main/kotlin/org/scribe/services/SimpleKeyboardIME.kt: (45, 5): 'hasTextBeforeCursor' overrides nothing
> e: .../Scribe-Android/app/src/main/kotlin/org/scribe/services/SimpleKeyboardIME.kt: (56, 5): 'commitPeriodAfterSpace' overrides nothing
> ```
> 
> Do you want to take a look at them? I'll get the PR template up now :)

I have fixed the error . I forgot to implement the functions after creating a branch from the new main.

**Comment by angrezichatterbox** [comment]
> PR template is [here](https://github.com/scribe-org/Scribe-Android/blob/main/.github/PULL_REQUEST_TEMPLATE.md), and you'll see the raw text in your next PR, @angrezichatterbox. Let me know if you have any suggestions for the template!

Thanks , It is very helpful

**Comment by andrewtavis** [comment]
I'll get to the review later this evening, @angrezichatterbox :)

**Comment by andrewtavis** [comment]
What would be an issue you'd think to look into next? Maybe #27 so we can finish that functionality up? There was a PR, but it only works for some devices.

**Review by andrewtavis — APPROVED** [review]
All's looking great, @angrezichatterbox! Thanks so much for the communication on this issue that got us to such a nice result 😊

**Pull request merged**
