### PR TITLE
design: align settings header with content

### PR DESCRIPTION
**Pull request by MostafaMohamed2002**
### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- Remove left margin from application page headers

|before| after |
|:----:|:---:|
|before|image|
| before | image |

### Related issue

-    #117

### CODE REVIEW

**Review by angrezichatterbox — COMMENTED** [review]
@MostafaMohamed2002 Thank you for the PR. The changes you have made look great.Could you try correcting the margins in the case of the About page and the pages directed from the about page?

**Comment by MostafaMohamed2002** [comment]
> @MostafaMohamed2002 Thank you for the PR. The changes you have made look great.Could you try correcting the margins in the case of the About page and the pages directed from the about page?

done 👌 , sorry for being late 😢
check it out below 😊

| | |
|---|---|
| Screenshot_1728308146 | Screenshot_1728308159 |
| Screenshot_1728308168 | Screenshot_1728308179 |

**Comment by andrewtavis** [comment]
Not late at all, @MostafaMohamed2002! Thanks for the further contributions :)

**Comment by angrezichatterbox** [comment]
> > @MostafaMohamed2002 Thank you for the PR. The changes you have made look great.Could you try correcting the margins in the case of the About page and the pages directed from the about page?
> 
> done 👌 , sorry for being late 😢 check it out below 😊
> 
> Screenshot_1728308146	Screenshot_1728308159
> Screenshot_1728308168	Screenshot_1728308179

This looks awesome @MostafaMohamed2002. Could you adjust the padding for the settings page a bit So that it matches the recycler view and the titles present in the page.

**Comment by MostafaMohamed2002** [comment]
i don't clearly understand what you want 😢

**Comment by angrezichatterbox** [comment]
> i don't clearly understand what you want 😢

Elements of the page could have more padding. Like the recycler view can you make the padding similar to the about page recycler view ?

**Comment by MostafaMohamed2002** [comment]
> > i don't clearly understand what you want 😢
> 
> Sorry I wasn't clear enough What I wanted to say is that the elements of the page could have more padding. Like the recycler view can you make the padding similar to the about page recycler view?

i think that's what you want , am i right ?

| before | after |
|-----|----|
| settings_page_before | settings_page_after |

**Comment by angrezichatterbox** [comment]
Sorry, your PR is fine. It was an issue with my simulator not showing the right padding. 
I think its good for merge :) . Thanks :)

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the great work here, @MostafaMohamed2002! Really grateful that you've already moved on to another issue as well 😊

**Pull request merged**
