### PR TITLE
Integrating bot to welcome

### PR DESCRIPTION
**Pull request by RishiKumarRay**

### CODE REVIEW

**Review by andrewtavis — CHANGES_REQUESTED** [review]
Could I get you to rename it `welcome.yml` for capitalization convention's sake? 😃

**Comment by RishiKumarRay** [comment]
@andrewtavis done , updated this. Thanks i missed that.

**Review by andrewtavis — APPROVED** [review]
Thank you, @RishiKumarRay! I'll write to close this in the issue :)

**Comment by RishiKumarRay** [comment]
@andrewtavis Issue , but i didn't opened any issue , just raised the PR? Should i add it ?

**Comment by andrewtavis** [comment]
@RishiKumarRay, I was referring to the [Scribe-iOS issue where you wrote me](https://github.com/scribe-org/Scribe-iOS/issues/111). Sorry for the confusion :)

**Comment by RishiKumarRay** [comment]
@andrewtavis No , problem 😀

**Pull request merged**
