### PR TITLE
Add Emoji Autosuggestion Buttons

### PR DESCRIPTION
**Pull request by Linfye**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
This PR adds buttons for emoji suggestions for mobile view and the logic to enable these buttons; the tablet view has not been added yet.

The current code implementation has some issues. I've added log statements as follows:
```
2024-09-26 20:59:18.321  3031-3031  EmojiButtonController   be.scri.debug            D  pluralBtn initialized: null
2024-09-26 20:59:18.322  3031-3031  EmojiButtonController   be.scri.debug            D  pluralBtn visibility: null
```
However, this code does not work properly. It seems that `EmojiButtonController.kt` has not successfully obtained the button elements from `keyboard_view_command_options.xml` and made modifications. I've tried many methods but to no avail. Can you help me with this?

### Related issue

-   #138

### CODE REVIEW

**Comment by angrezichatterbox** [comment]
Sorry for the delay in my response. I had some college work yesterday. So you have two choices to prevent those from going null. You could initialize the controller in the individual keyboard IME class and accordingly use them. The binding is inflated only in the individual keyboard IME. Alternatively, you could move the controller code to the simple keyboard IME abstract class that consists of the keyboard's current functions and then call them from the individual keyboard IME.

**Comment by angrezichatterbox** [comment]
> Sorry for the delay in my response. I had some college work yesterday. So you have two choices to prevent those from going null. You could initialize the controller in the individual keyboard IME class and accordingly use them. The binding is inflated only in the individual keyboard IME. Alternatively, you could move the controller code to the simple keyboard IME abstract class that consists of the keyboard's current functions and then call them from the individual keyboard IME.

The binding has to be passed as a parameter to the functions if the second thought is considered. I think it is the same for the first way but not so sure.

**Comment by andrewtavis** [comment]
Within 24 hours isn't a delayed response, @angrezichatterbox :) School's important and certainly the priority 😊

Thanks for the suggestions!

**Comment by andrewtavis** [comment]
Hey @Linfye 👋 Checking in to see what your thoughts are on @angrezichatterbox's feedback :) Let's us know if you need any support here!

Hope you're well 😊

**Comment by Linfye** [comment]
I apologize for not informing you earlier. I had to return to my hometown recently to deal with some urgent matters, and I didn’t have the time or proper environment to work, which is why I haven’t been able to respond. I’ll be returning to school tomorrow and should be able to resume work within the next couple of days.

I'm very sorry for making you wait so long.

**Comment by andrewtavis** [comment]
No need to apologize whatsoever, @Linfye! The assumption on my part was that something was up, so wanted to check in. Hope that you're doing ok, and take your time jumping back in here :)

**Comment by Linfye** [comment]
I put the controller code in the SimpleKeyboardIME. But it seemed that `initializeEmojiButtons` was never called while running the App according to logcat. Can you help me with this? @angrezichatterbox Thanks!

**Comment by angrezichatterbox** [comment]
> I put the controller code in the SimpleKeyboardIME. But it seemed that `initializeEmojiButtons` was never called while running the App according to logcat. Can you help me with this? @angrezichatterbox Thanks!

I will look into it and get back to you :)

**Comment by angrezichatterbox** [comment]
> I put the controller code in the SimpleKeyboardIME. But it seemed that `initializeEmojiButtons` was never called while running the App according to logcat. Can you help me with this? @angrezichatterbox Thanks!

The Simple Keyboard IME is an abstract class that consists of any functions that are being used by all the languages. The individual languages have their codebase for the setup of the keyboard. You could call the function from the individual keyboard IME. Also, could you use binding instead of calling using findViewById? Thanks :)  
Overall everything looks nice @Linfye :)   These changes would make it functional hopefully.

**Comment by Linfye** [comment]
@angrezichatterbox Now the `initializeEmojiButtons` can get the buttons but `updateButtonVisibility` returned null buttons. Can you give me some instructions? Thanks a lot!

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox Now the `initializeEmojiButtons` and `updateButtonVisibility` can be called in the app. But `updateButtonVisibility` returned null buttons Can you give me some instructions? Thanks a lot! 
> 
> 
> 
> And in my development branch, whenever I press the backspace key, the built app crashes. Do you have this issue? If so, we can file a bug report.
> 
> 
> 
> cc: @andrewtavis 

I will reply for the first thing later on as I'm travelling. 
As for the back space crash. Could u try pull the new main and rebasing your branch with new main. Or merge main into your branch. It was fixed recently.

**Comment by Linfye** [comment]
I've changed to another way of passing parameters, allowing `EnglishKeyboardIME` to access the status of the Switch in `LanguageSettingsFragment`, which can solve the previous issue.

However, as shown in #186, this problem also exists in the latest main branch. So to test the current feature, you should return to the phone's Home screen without going back to the Settings page after modifying the Switch, and then open the keyboard to test. I don't know the cause of #186; the Autosuggest Emojis Switch was also added by me referring to the Double Space Peroids code, but this problem occurred.

I've rebased the code from the main branch, but the Backspace crash issue that I mentioned earlier still exists. Have you tested it on your machine? If you have, it might just be my problem, and I will try to resolve it later.

The current code implements two Emoji versions for the phone view. If this works fine for you, I would like to merge the current PR first. For the three Emoji versions of the tablet view, I think a new issue can be created for other contributors to refer to and work on for hacktoberfest. Of course, if no one takes it on, I can handle it.

Thank you for your help on this issue. @angrezichatterbox @andrewtavis

**Comment by angrezichatterbox** [comment]
> I've changed to another way of passing parameters, allowing `EnglishKeyboardIME` to access the status of the Switch in `LanguageSettingsFragment`, which can solve the previous issue.
> 
> However, as shown in #186, this problem also exists in the latest main branch. So to test the current feature, you should return to the phone's Home screen without going back to the Settings page after modifying the Switch, and then open the keyboard to test. I don't know the cause of #186; the Autosuggest Emojis Switch was also added by me referring to the Double Space Peroids code, but this problem occurred.
> 
> I've rebased the code from the main branch, but the Backspace crash issue that I mentioned earlier still exists. Have you tested it on your machine? If you have, it might just be my problem, and I will try to resolve it later.
> 
> The current code implements two Emoji versions for the phone view. If this works fine for you, I would like to merge the current PR first. For the three Emoji versions of the tablet view, I think a new issue can be created for other contributors to refer to and work on for hacktoberfest. Of course, if no one takes it on, I can handle it.
> 
> Thank you for your help on this issue. 😊 @angrezichatterbox @andrewtavis

For #186 the value gets changed however there is a typo in the value that is checked is retrieving 
isChecked = sharedPref.getBoolean("autosuggest_emojis_$language", true),
Could you change this to emoji_suggestions_$language

**Comment by Linfye** [comment]
Yes, it crashed every time. This issue happened after this.
image
I don't know the exact commit.

**Comment by angrezichatterbox** [comment]
https://github.com/scribe-org/Scribe-Android/blob/6758b8faa659047028927e72f8a17b0175c3b0a2/app/src/main/java/be/scri/services/EnglishKeyboardIME.kt#L193-L214


Could u replace for everytime the Scribe State is idle for binding to be null

**Comment by Linfye** [comment]
You mean like this? but it still crashed in English keyboard. @angrezichatterbox

**Comment by angrezichatterbox** [comment]
> You mean like this? but it still crashed in English keyboard. @angrezichatterbox

Pass it like binding = null

**Comment by Linfye** [comment]
OK, problem solved. Thanks!

**Comment by andrewtavis** [comment]
Are we good for a final check here? Thank you both for the great collaboration!

**Comment by andrewtavis** [comment]
And does this also solve #186?

**Comment by Linfye** [comment]
> And does this also solve #186?

Yes, you can close both issues together after this pull request is successfully merged. 😊

**Comment by angrezichatterbox** [comment]
> > And does this also solve #186?
> 
> Yes, you can close both issues together after this pull request is successfully merged. 😊

Could u also add the initialization and update to the other Keyboard IME

**Comment by Linfye** [comment]
> > > And does this also solve #186?
> > 
> > 
> > Yes, you can close both issues together after this pull request is successfully merged. 😊
> 
> Could u also add the initialization and update to the other Keyboard IME

Are you referring to languages other than English and German?

**Comment by angrezichatterbox** [comment]
> > > > And does this also solve #186?
> > > 
> > > 
> > > Yes, you can close both issues together after this pull request is successfully merged. 😊
> > 
> > 
> > Could u also add the initialization and update to the other Keyboard IME
> 
> Are you referring to languages other than English and German?

Yes

**Comment by Linfye** [comment]
👌

**Comment by andrewtavis** [comment]
Could we get the most recent conflicts fixed and then I'll do a final review? :)

**Comment by Linfye** [comment]
Okay, could you resolve the conflicting code to keep these features? I don't have the permission to do this. 😊

> Could we get the most recent conflicts fixed and then I'll do a final review? :)

**Comment by andrewtavis** [comment]
You should be able to pull the main branch into your branch and then resolve the conflicts, @Linfye :) We can do it for you if you'd like us to though 😊

**Comment by Linfye** [comment]
> You should be able to pull the main branch into your branch and then resolve the conflicts, @Linfye :) We can do it for you if you'd like us to though 😊

Oh, I know now. But it's midnight here. 💤 If you have time, could you do this? Or wait until I do it tomorrow.

**Comment by andrewtavis** [comment]
Thanks for getting to this, @Linfye! Quite busy with all the activity in the projects right now, so this really does help 😊

**Comment by andrewtavis** [comment]
Let us know when it's ready :)

**Comment by Linfye** [comment]
I think I've resolved the code conflicts and also implemented the emoji autosuggest button for tablets now. Could you find some time to review it? If there are any issues, please let me know at any time. 😊

**Comment by andrewtavis** [comment]
Could we ask you for one more check here, @angrezichatterbox? :)

**Comment by angrezichatterbox** [comment]
> Could we ask you for one more check here, @angrezichatterbox? :)

I'll check it again by tomorrow afternoon. I'm travelling right now :)

**Comment by angrezichatterbox** [comment]
@Linfye, could we make the button visibility based on the application's state? Currently, when users select a command, the Plural Button gets hidden behind the auto-suggestions. Additionally, once the user returns to the idle state, the auto-suggestions button disappears.
A potential solution would be to link the button visibility to the `updateUI()` function or to integrate it with the toolbar or command view setup or switch functions. This way, we can ensure that the buttons are consistently visible and appropriately reflect the current state of the keyboard.

**Comment by Linfye** [comment]
Thanks, I didn't notice this before. I'll fix this later today. @angrezichatterbox

**Comment by Linfye** [comment]
I've fixed the bug, and now the emoji autosuggest buttons appear only when in the SELECT_COMMAND state. If you there‘s any other issues, please feel free to let me know. :)

**Comment by angrezichatterbox** [comment]
I guess it should be shown only in idle state.

**Comment by andrewtavis** [comment]
Hehe sorry I need to read a bit better. Absolutely correct, @angrezichatterbox :) Should only be shown on idle 😊

**Comment by Linfye** [comment]
Now the autosuggest buttons show in idle state. 😊

**Review by andrewtavis — APPROVED** [review]
Looking really great to me, @Linfye! Thanks so much for the dedication in getting this done 😊 So awesome to have you as such a reliable contributor here :) :)

**Pull request merged**
