### PR TITLE
Enable and disable comma and period on ABC

### PR DESCRIPTION
**Pull request by henrikth93**
This commit will implement the functionality for the toggle"disable/enable comma and period on ABC"-option

### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Related issue

-   #148

### CODE REVIEW

**Comment by andrewtavis** [comment]
@angrezichatterbox, one thing to note here is that a lot of XML layouts are being added here. Not sure if this is something that could be improved by a switch to Compose, but this would maybe be an argument for making the switch if so. Other suggestions would be welcome!

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, one thing to note here is that a lot of XML layouts are being added here. Not sure if this is something that could be improved by a switch to Compose, but this would maybe be an argument for making the switch if so. Other suggestions would be welcome!

I think it is always a better decision to switch to compose. I just had the query of whether there would be any issues handling compose views with the Keyboard IME and its ease and most of the keyboard are in XML. However we could try it out for sure Migrating it to compose.

**Comment by andrewtavis** [comment]
In your opinion though we're good to merge this in and then we can include it in the migration later, @angrezichatterbox? :)

**Comment by andrewtavis** [comment]
@henrikth93, do you want to address the change to the Toast as @angrezichatterbox indicated and then we'll bring this in? :)

**Comment by henrikth93** [comment]
Sure, gonna try and do this this evening.

Den mån 9 dec. 2024 kl 19:06 skrev Andrew Tavis McAllister <
***@***.***>:

**Comment by andrewtavis** [comment]
@henrikth93 and @angrezichatterbox: Can we take a look at why the tests are failing here now? :)

**Comment by angrezichatterbox** [comment]
> @henrikth93 and @angrezichatterbox: Can we take a look at why the tests are failing here now? :)

The errors displayed were network-related issues. The workflow successfully executes when it’s rerun.

**Comment by andrewtavis** [comment]
Nice, I assumed that but then they failed on me a second time :) Thanks, @angrezichatterbox!

**Review by andrewtavis — APPROVED** [review]
All's working well here now 😊 Thanks much for the great work here, @henrikth93, as well as the quick reaction to @angrezichatterbox's review :) Amazing to have this functionality in both apps now so the keyboards are more accessible to those switching devices!

**Pull request merged**
