### PR TITLE
Migrate third-party license xml to compose

### PR DESCRIPTION
**Pull request by growabeard**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This is creating a Jetpack Compose version of the third-party licenses screen.

It adds the theming and font and styling basics of Compose for use on more screens as well.

Tested by running the app and changing themes and comparing with the previous version and figma designs.

third_party_dark
third_party_light

### Related issue

-   #217

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for the PR, @growabeard! Really great to get this conversion off the ground 😊 Would you be able to fix the merge conflicts?

**Comment by andrewtavis** [comment]
Is this ready for a review now, @growabeard? :)

**Review by angrezichatterbox — COMMENTED** [review]
Great PR @growabeard. This would be a significant PR as it lays the foundation for the project conversion to Jetpack Compose. Thank you very much :) 

I have some suggestions for the file structure. Could the UI directory have an extra screens directory, and could the third-party screen be put there instead? The card view could be broken into the component folder so that it can be reused for the other pages. Please do share any suggestions on making it into this structure.

**Comment by angrezichatterbox** [comment]
Also, I am not sure about the naming for Compose but is it not a convention to use lowerCamelCase for naming in Compose?

**Comment by angrezichatterbox** [comment]
> Is this ready for a review now, @growabeard? :)

I’ve reviewed it, as I assumed it was ready. Happy to re-review if it is not ready for review yet.

**Comment by growabeard** [comment]
> Also, I am not sure about the naming for Compose but is it not a convention to use lowerCamelCase for naming in Compose? 

According to [the docs](https://android.googlesource.com/platform/frameworks/support/+/androidx-main/compose/docs/compose-api-guidelines.md#naming-unit-composable-functions-as-entities), it's suggested to use PascalCase for naming Composable functions. It's not required.

I'm open to either option, I just started with the naming convention from Google.

**Comment by growabeard** [comment]
> > Is this ready for a review now, @growabeard? :)
> 
> I’ve reviewed it, as I assumed it was ready. Happy to re-review if it is not ready for review yet. 

I have had this issue in the past, do you want me to leave a comment that it's ready or do some other signal once it's ready for review?

**Comment by andrewtavis** [comment]
Leaving a comment to say it's ready for review is always helpful, but I wouldn't call it an issue, @growabeard 😊

Let's stick to Google standards as much as we can here, so are we good with staying with PascalCase?

**Comment by angrezichatterbox** [comment]
> Let's stick to Google standards as much as we can here, so are we good with staying with PascalCase?

Yes, It makes sense to follow the Google standards. 

> I have some suggestions for the file structure. Could the UI directory have an extra screens directory, and could the third-party screen be put there instead? The card view could be broken into the component folder so that it can be reused for the other pages. Please do share any suggestions on making it into this structure.

@andrewtavis @growabeard What are your opinions on the above? Should we have a folder structure like this or some other structure should be followed? 

- ui
  - theme
    - Color.kt
    - Typography.kt
    - Shape.kt
    - Theme.kt
  - screens
    - HomeScreen.kt
  - components
    - CustomBox.kt

**Comment by growabeard** [comment]
> > Let's stick to Google standards as much as we can here, so are we good with staying with PascalCase?
> 
> Yes, It makes sense to follow the Google standards.
> 
> > I have some suggestions for the file structure. Could the UI directory have an extra screens directory, and could the third-party screen be put there instead? The card view could be broken into the component folder so that it can be reused for the other pages. Please do share any suggestions on making it into this structure.
> 
> @andrewtavis @growabeard What are your opinions on the above? Should we have a folder structure like this or some other structure should be followed?
> 
> * ui
>   
>   * theme
>     
>     * Color.kt
>     * Typography.kt
>     * Shape.kt
>     * Theme.kt
>   * screens
>     
>     * HomeScreen.kt
>   * components
>     
>     * CustomBox.kt

Totally agree with this idea. Someone can create the components folder again when it's needed for common components.

**Comment by angrezichatterbox** [comment]
Once this PR is closed, we should set up linting checks for Compose using either [Twitter Compose Lint](https://twitter.github.io/compose-rules/ktlint/) or [Slack Compose Lint](https://slackhq.github.io/compose-lints/) before more Compose code gets merged.

**Comment by andrewtavis** [comment]
I would prefer to use Slack Compose Lint if functionality is similar. If that's ok, do you want to make an issue for that, @angrezichatterbox?

**Comment by angrezichatterbox** [comment]
> I would prefer to use Slack Compose Lint if functionality is similar. If that's ok, do you want to make an issue for that, @angrezichatterbox?

Yes, it makes sense to use Slack Compose Lint, as it is still being maintained. I will create an issue for it.

**Review by andrewtavis — APPROVED** [review]
Bringing this first one in 😊 Glad to have the work starting on this, and thanks so much for the contribution, @growabeard!

**Pull request merged**
