### PR TITLE
Henrikth93 android margin #144

### PR DESCRIPTION
**Pull request by henrikth93**
### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

-   #144

### CODE REVIEW

**Review by angrezichatterbox — COMMENTED** [review]
@henrikth93 Thank you very much for the PR.  

Could the text View margins be changed instead of card view, or could the text view margins be changed to match the parent so that we would cover the entire width of the parent, which is card view. We would, however, then have to find ways to adjust so that the text does not go under the corner image.

**Comment by henrikth93** [comment]
> @henrikth93 Thank you very much for the PR.
> 
> Could the text View margins be changed instead of card view, or could the text view margins be changed to match the parent so that we would cover the entire width of the parent, which is card view. We would, however, then have to find ways to adjust so that the text does not go under the corner image.

I am thinking if one way to do it is to split the original texts into two parts, one parts which is adjacent to the corner image, and has different layout settings to prevent them from overlapping, and a different text view which fills out the whole box

**Comment by angrezichatterbox** [comment]
> > @henrikth93 Thank you very much for the PR.
> > Could the text View margins be changed instead of card view, or could the text view margins be changed to match the parent so that we would cover the entire width of the parent, which is card view. We would, however, then have to find ways to adjust so that the text does not go under the corner image.
> 
> I am thinking if one way to do it is to split the original texts into two parts, one parts which is adjacent to the corner image, and has different layout settings to prevent them from overlapping, and a different text view which fills out the whole box

Yes, That would work fine as well. But it would depend on how the text is presented for now. If all the text is present together, we could try passing from Kotlin code where we would split the text and then pass to the text views we have in the XML.

**Comment by andrewtavis** [comment]
Let's make sure to remember that the texts need to be in one string for Scribe-i18n :) Anything that generally works is fine. Honestly maybe a redesign to get rid of those corner triangles would be good, but that's for maybe post Outreachy :)

**Comment by angrezichatterbox** [comment]
@henrikth93 It looks good now. What do you think would it  be better if the card view margin end is changed to 8 dp or 9 dp?

**Comment by henrikth93** [comment]
> @henrikth93 It looks good now. The text does not get hidden in most languages . What do you think would it be better if the card view margin end is changed to 8 dp or 9 dp?

Changed it to 10.

**Comment by angrezichatterbox** [comment]
It looks great to me now  Thanks :)

**Review by andrewtavis — APPROVED** [review]
Thanks for the changes, @henrikth93, and also for the review, @angrezichatterbox! Is looking really great 😊

**Pull request merged**
