### PR TITLE
Add Autosuggest emojis menu item

### PR DESCRIPTION
**Pull request by Linfye**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR add an menu item to trigger emoji autosuggestions and a Toast message while switching.
### Related issue

-   #64

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for fixing the linting errors, @Linfye!

**Review by angrezichatterbox — COMMENTED** [review]
Thank you for the work @Linfye. The PR is quite good :). A Toast Message that shows up on the change of the Switch. @andrewtavis is this needed to indicate the change along with the Switch changing?

**Comment by andrewtavis** [comment]
@angrezichatterbox, I don't think it hurts to have it in there :) We can remove it in #66 :)

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, I don't think it hurts to have it in there :) We can remove it in #66 :)

True, I just wanted to clarify whether it should be added to the other switch as well.

**Comment by andrewtavis** [comment]
Yes I was thinking the same. If having them in there would give people a head start on future implementations of the menu options, then feel free to send along a PR to add the toasts, @angrezichatterbox :)

**Comment by angrezichatterbox** [comment]
> Yes I was thinking the same. If having them in there would give people a head start on future implementations of the menu options, then feel free to send along a PR to add the toasts, @angrezichatterbox :)

Yes, it would give some idea about what the change should be for each language and more clarity during development. Should I make the change to the other switch and add to this PR.

**Comment by andrewtavis** [comment]
Sure thing, @angrezichatterbox! Sounds perfect. I'll bring this in after.

**Comment by angrezichatterbox** [comment]
It seems I don't have permission to add to this PR. I will add it to my other PR.

**Comment by andrewtavis** [comment]
Or I'll merge in that one soon. Feel free to open a new one, @angrezichatterbox!

**Review by andrewtavis — APPROVED** [review]
Great contribution, @Linfye! Really seems like you're starting to get the hang of Scribe-Android 😊 Awesome to see!

**Pull request merged**
