### PR TITLE
Add suppressions

### PR DESCRIPTION
**Pull request by henrikth93**
This commit will add suppressions for "Long method"

### Contributor checklist

-   [] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Related issue

-   #111

### CODE REVIEW

**Comment by andrewtavis** [comment]
@angrezichatterbox, are you good with the suppressions here, or should any of these be broken up?

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox, are you good with the suppressions here, or should any of these be broken up?

I suggested using Suppress for now as some of the classes would be modified or deleted. @henrikth93 Apologies for earlier stating that MyKeyboardView has to be suppressed for handling LongMethod. We could refractor a few of its functions but we would have to consider a throughout check of whether the keyboard is being drawn properly. Other classes for now I think its fine to have them suppressed as it would be removed later on.

**Comment by andrewtavis** [comment]
Now I'm just confused 😅 Sorry, so we need to be explicit to say that we want tests to run? And the test was passing, then I removed the true entries because I thought it would default to being ran, and then the test failed, and now I've added them back in and it fails still?

**Comment by angrezichatterbox** [comment]
> Now I'm just confused 😅 Sorry, so we need to be explicit to say that we want tests to run? And the test was passing, then I removed the true entries because I thought it would default to being ran, and then the test failed, and now I've added them back in and it fails still?

We have to rebase the branch with the main and then fix the remaining linting issues. This would fix the problem.  I had a similar issue with my PR where I was shown a linting issue in a line that was not present in my branch.

**Review by andrewtavis — APPROVED** [review]
Beautiful stuff, @henrikth93! 🚀 Thanks for the quick fix here and cleaning my mess :)

**Pull request merged**
