### PR TITLE
Migrate the settings page to Jetpack Compose

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description

The pull request moves the settings page to Jetpack Compose. A separate issue would be created to migrate the Language settings page to Jetpack Compose since it’s too large to fit within the same PR. 

### Related issue

#247

### CODE REVIEW

**Comment by angrezichatterbox** [comment]
Happy to make changes to any visual detail that I might have missed while migrating to Jetpack Compose.

**Comment by andrewtavis** [comment]
Generally all's looking really good, @angrezichatterbox :) One thing I'm seeing is that the divider line for language sub menus isn't quite right? Should be more in the middle? See below:

Screenshot 2024-11-27 at 19 56 56

Aside from that, would you suggest that the toggles change style as they have? The new versions have a cta orange outline if they're not active rather than just a grey background, and there's also padding around the circular interactive element of the toggle, where before it there was no padding. Happy to hear your feedback on this and we can go from there! Would just be good to make sure that iOS and Android are the same, but we can work on it :)

**Comment by angrezichatterbox** [comment]
> Generally all's looking really good, @angrezichatterbox :) One thing I'm seeing is that the divider line for language sub menus isn't quite right? Should be more in the middle? See below:
> 
> Screenshot 2024-11-27 at 19 56 56
> 
> Aside from that, would you suggest that the toggles change style as they have? The new versions have a cta orange outline if they're not active rather than just a grey background, and there's also padding around the circular interactive element of the toggle, where before it there was no padding. Happy to hear your feedback on this and we can go from there! Would just be good to make sure that iOS and Android are the same, but we can work on it :)

So currently I am directly using Material Switches I would make it to use the earlier switch. I missed it during the migration. I would also make the divider towards the centre. Thanks :)

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the word here, @angrezichatterbox! In looking at [the toggle designs I made](https://www.figma.com/design/c8945w2iyoPYVhsqW7vRn6/scribe_public_designs?node-id=513-2072&t=IC3mMCgbuXzrmjUe-1) the new versions are much better than the old ones 😊 Thanks for the attention to detail here and continuing the migration!

**Pull request merged**
