### PR TITLE
feat:Implemented back button in the action bar

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

- Implemented the Back Button in the action bar 
- Made the Action Bar similar to Scribe-iOS

### Related issue

-   #76

### CODE REVIEW

**Comment by andrewtavis** [comment]
This is looking so good, @angrezichatterbox! It's really looking like Scribe-iOS finally 🤩 One thing to note: Would it be possible for the action bar to have a bit of a margin at the top? Maybe bring everything down like a centimeter or whatever looks ok on your end? The headers seem a bit high, and the back buttons like of blend in with the icons at the top of the screen.

After this we'll be good to merge! 😊

**Comment by angrezichatterbox** [comment]
> This is looking so good, @angrezichatterbox! It's really looking like Scribe-iOS finally 🤩 One thing to note: Would it be possible for the action bar to have a bit of a margin at the top? Maybe bring everything down like a centimeter or whatever looks ok on your end? The headers seem a bit high, and the back buttons like of blend in with the icons at the top of the screen.
> 
> After this we'll be good to merge! 😊



Screenshot 2024-09-04 at 9 03 50 AM
Screenshot 2024-09-04 at 9 10 10 AM

How does this look? Should I make them come slightly below in the case of the subpages?

**Comment by andrewtavis** [comment]
Is looking great, @angrezichatterbox! The only thing I'd change is that sub headers like `How we work together` should be move to the right a bit so they're inline with the page header and the back button, and the back button in your screens should be black as it's light mode, so maybe check that the colors for those are being applied correctly 😊

**Review by andrewtavis — APPROVED** [review]
All looking really great, @angrezichatterbox! Really is coming along so well :) Just need the logo and the directions for the installation to be a bit more explicit, and then it'll really be looking like Scribe 😊

**Pull request merged**
