### PR TITLE
Combining and pulling members up to the superclass.

### PR DESCRIPTION
**Pull request by growabeard**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR is fixing the detekt issue TooManyFunctions for the various language KeyboardIME classes.
Disclaimer: yes I know this is pulling up functions to the parent class which already violates the detekt issues. However, I think there is something to be gained in clearing up duplicate code.

To test: turn off the detekt TooManyFunctions issue and run `./gradlew detekt` and observe the output on main branch.

### Related issue

-   #107

### CODE REVIEW

**Comment by andrewtavis** [comment]
Checking on this, @growabeard: We could close #203 after this?

**Comment by growabeard** [comment]
There are 3 more classes from that PR I want to use as reference for a second PR for this issue. I can close that PR though, it was too big and I wanted to split up the work.

**Comment by andrewtavis** [comment]
Sounds good, @growabeard, and I do definitely agree that we should try to centralize as much of this code as possible seeing as how the number of keyboards will increase over time :)

**Comment by andrewtavis** [comment]
Are we ready for a review here, @growabeard? :)

**Comment by growabeard** [comment]
> Are we ready for a review here, @growabeard? :)

Please do!

**Review by angrezichatterbox — APPROVED** [review]
Impressive work @growabeard. The change you have made is very important as the project moves forward as it helps to avoid the boilerplate code that was present in each class. Thank you!

**Review by andrewtavis — APPROVED** [review]
Really amazing work, @growabeard 😊 Thanks so much for the focus you put into simplifying the project down. This will make expanding the project a so much easier post release 🚀

**Pull request merged**
