### PR TITLE
feat:Use Fragments for navigation

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Contributor checklist
-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
- The pull request replaces activities with fragments for better navigation. A view pager has been used to make the swipe gestures for movements similar to Scribe-iOS. Through the pull request, the Bottom navigation bar is not being reconstructed every time the user changes the page. 
### Related issue

-   #71

### CODE REVIEW

**Comment by andrewtavis** [comment]
Nice, @angrezichatterbox :) Only one file with merge conflicts!

**Comment by angrezichatterbox** [comment]
> Nice, @angrezichatterbox :) Only one file with merge conflicts!

Yes. I will be fixing it within some time and I will comment here when its ready for review :).

**Comment by andrewtavis** [comment]
Perfect, thanks so much! I'll plan to bring it in later today if you send the next commit :)

**Comment by angrezichatterbox** [comment]
I have made the necessary changes. The PR is ready for review. :)

**Comment by andrewtavis** [comment]
Ok the other PR is in, @angrezichatterbox :) Two files have conflicts, but then I'll bring this in once they're fixed 😊 Thanks for the coordination here!

**Comment by andrewtavis** [comment]
Let me know when it's ready for a review, @angrezichatterbox :)

**Review by andrewtavis — APPROVED** [review]
Working really really well, @angrezichatterbox! Such an improvement on the experience. Thanks for looking into how we can improve it and setting everything up!

One note: We don't have a back button in sub menus right now. I'll make an issue for that 😊

**Pull request merged**
