### PR TITLE
fixed linting issue caused by the functions parameter not being used …

### PR DESCRIPTION
**Pull request by Yashvardhan-17**
…by function

### Contributor checklist

-   [] This pull request is on a [feature/99-unused-function-parameter-lint](https://github.com/Yashvardhan-17/Scribe-Android/tree/feature/99-unused-function-parameter-lint) and not the main branch

---

### Description
Resolved the linting issue that arose from unused function parameters by removing them from the relevant functions. Additionally, updated all associated function calls to ensure they align with the modified function signatures.

### Related issue

-   #ISSUE_NUMBER
-  #99

### CODE REVIEW

**Comment by andrewtavis** [comment]
Looks like there are some merge conflicts here 🤔 @angrezichatterbox, do you want to give some suggestions for how @Yashvardhan-17 can fix them?

**Comment by angrezichatterbox** [comment]
> Looks like there are some merge conflicts here 🤔 @angrezichatterbox, do you want to give some suggestions for how @Yashvardhan-17 can fix them?

@Yashvardhan-17 
In the case of the merge conflicts that are present in the individual language IME. U have to accept the Current change and replace the parameter in the current Change instead of accepting your change.

**Comment by andrewtavis** [comment]
Are you planning on opening a new PR, @Yashvardhan-17? This is also totally fine :)

**Comment by Yashvardhan-17** [comment]
@angrezichatterbox I have worked on this PR only, thought of new but this worked :).

**Comment by angrezichatterbox** [comment]
@Yashvardhan-17 I have been getting an error with clips table doesn't exist. I am not exactly sure if it's an issue from my side.

**Review by andrewtavis — APPROVED** [review]
Thanks so much for the quick work here and reacting to the directions to fix issues so well, @Yashvardhan-17! Two great first contributions 😊

**Pull request merged**
