### PR TITLE
Play Icon When in a Command Mode

### PR DESCRIPTION
**Pull request by Linfye**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description
This PR changes enter icon to play button when in a command mode.

### Related issue

-   #160

### CODE REVIEW

**Comment by Linfye** [comment]
The creation process of the keyboard is implemented by a helper, and I haven't found a suitable way to pass the `isCommandMode` parameter. After modifying the `isCommandMode` value in SimpleKeyboardIME and recreating the keyboard, it seems that the parameter is reset, and I don't know how to solve this. Could you help me with this? Thanks! :) @andrewtavis

**Comment by andrewtavis** [comment]
CC also @angrezichatterbox as I'm at work atm :) I'll take a look tonight or over the weekend, @Linfye! Thank you!

**Comment by angrezichatterbox** [comment]
I am not sure we have any easy ways of passing the command boolean. However, I have another way in which we could do it. One method is to set a custom state within the keyboard. So for eg if we use the  EditorInfo.IME_ACTION_UNSPECIFIED is the condition for setting the icon of the enter key to the Play Icon. Now there is the setEnterKeyColor function use it to set the mEnterKeyType as that specific type. Now create a function to set the enter key icon using this logic in MyKeyboard.kt and call this function after setting the mEnterKey type. You can use any custom type to do it.

I am happy to explain in more detail :)

**Comment by Linfye** [comment]
> I am not sure we have any easy ways of passing the command boolean. However, I have another way in which we could do it. One method is to set a custom state within the keyboard. So for eg if we use the EditorInfo.IME_ACTION_UNSPECIFIED is the condition for setting the icon of the enter key to the Play Icon. Now there is the setEnterKeyColor function use it to set the mEnterKeyType as that specific type. Now create a function to set the enter key icon using this logic in MyKeyboard.kt and call this function after setting the mEnterKey type. You can use any custom type to do it.


I had considered this method initially, but I thought that modifying the built-in state might not be a common practice in Android development (I'm not quite sure about this). Since you suggested it, I can give it a try. Thank you! :)

**Comment by angrezichatterbox** [comment]
> > I am not sure we have any easy ways of passing the command boolean. However, I have another way in which we could do it. One method is to set a custom state within the keyboard. So for eg if we use the EditorInfo.IME_ACTION_UNSPECIFIED is the condition for setting the icon of the enter key to the Play Icon. Now there is the setEnterKeyColor function use it to set the mEnterKeyType as that specific type. Now create a function to set the enter key icon using this logic in MyKeyboard.kt and call this function after setting the mEnterKey type. You can use any custom type to do it.
> 
> I had considered this method initially, but I thought that modifying the built-in state might not be a common practice in Android development (I'm not quite sure about this). Since you suggested it, I can give it a try. Thank you! :)

You could also set a companion object as a new type and set the key type as that from the setEnterKeyColor function.

**Comment by Linfye** [comment]
@angrezichatterbox Sorry for the delay, I've been busy with school matters lately. And thank you very much for your help! 

Could you review the current code? 😊

**Comment by andrewtavis** [comment]
Functionality wise it looks good to me, @Linfye :) Might be nice if we could have the play icon moved a bit to the right - say 10% of the button's width, as with these sorts of icons if we actually center it it doesn't "look centered" :) This could be another task if you'd like it to be though!

**Comment by Linfye** [comment]
> Functionality wise it looks good to me, @Linfye :) Might be nice if we could have the play icon moved a bit to the right - say 10% of the button's width, as with these sorts of icons if we actually center it it doesn't "look centered" :) This could be another task if you'd like it to be though!

Yes, I noticed this issue before but forgot to mention it here. I can update this icon by adding a transparent margin on the left side to resolve it. What do you think? :)

**Comment by andrewtavis** [comment]
That'd be perfect, @Linfye! Thank you!

**Review by angrezichatterbox — COMMENTED** [review]
@Linfye Everything looks nice. We could make the visual changes as suggested. We also have an edge case to deal with which comes which the approach. This could be an issue which could be created and worked on later on. 

So currently when the user closes the keyboard when in any of the modes where the play icon is shown. If the user switches to an app and gets back to keyboard the play icon disappears and it would become again the icon as per the Editor Info. 

A thing we could do is to switch the mode to idle when the user exits off the keyboard. Would love to hear about this specific issue. 

Other than this amazing work @Linfye

**Comment by andrewtavis** [comment]
Switching to idle when the user navigates away makes sense to me, @angrezichatterbox 😊

**Comment by angrezichatterbox** [comment]
> Switching to idle when the user navigates away makes sense to me, @angrezichatterbox 😊

Yes it makes sense. Should we create an issue for correcting this edge case after this PR is merged ?

**Comment by andrewtavis** [comment]
Either or. @Linfye, if you want to include it in here, then by all means, or if not let's make the issue 😊

**Comment by angrezichatterbox** [comment]
@Linfye Would u like to bring it in or should I add it to this PR :) Happy to add it to the PR :)

**Comment by Linfye** [comment]
> @Linfye Would u like to bring it in or should I add it to this PR :) Happy to add it to the PR :)

Yes, I'd like to solve this.

**Comment by Linfye** [comment]
@angrezichatterbox I've tried to change the keyboard state using `onFinishInput`, but I'm not sure how to update the UI. There's some strange functionality disorder. Would you like to take over this?

**Comment by angrezichatterbox** [comment]
> @angrezichatterbox I've tried to change the keyboard state using `onFinishInput`, but I'm not sure how to update the UI. There's some strange functionality disorder. Would you like to take over this?

I would look into it and would get back to you.

**Comment by angrezichatterbox** [comment]
So the function that was being run when the input view  is closed was onFinishInputView(). I have implemented the changes. I just checked the codebase a bit more now. Thanks for replacing the deprecated setBackgroundDrawable(). 

It is ready for review @andrewtavis

**Pull request merged**
