### PR TITLE
Fix TooManyFunctions in Fragments and MainActivity.

### PR DESCRIPTION
**Pull request by growabeard**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

I have gone through the fragments package and the MainActivity to fix the TooManyFunctions detekt issue by refactoring common code and moving out code that was doing work outside the responsibility of the class it was previously in (example: MainActivity getting the preferences for dark mode, when that should be owned by the PreferencesHelper.)

I have added an annotation to the remaining classes (`SimpleKeyboardIME` and `MyKeyboardView`) because they are very large and I'm not sure if they can be split up.

### Related issue

-   #107

### CODE REVIEW

**Comment by angrezichatterbox** [comment]
Screenshot 2024-10-24 at 8 55 16 PM
Screenshot 2024-10-24 at 8 55 22 PM

Could you look into why the action bar title is not aligned?

**Comment by growabeard** [comment]
> Screenshot 2024-10-24 at 8 55 16 PM Screenshot 2024-10-24 at 8 55 22 PM
> Could you look into why the action bar title is not aligned?

Nice find @angrezichatterbox, I flipped the margin settings when I combined them. It should be fIxed now.

**Comment by angrezichatterbox** [comment]
> > Could you look into why the action bar title is not aligned?
> 
> Nice find @angrezichatterbox, I flipped the margin settings when I combined them. It should be fixed now.

Everything else looks good to me @growabeard. It is good for merge. Thanks :)

**Comment by andrewtavis** [comment]
Thanks for the work here @growabeard, and also for the thorough review, @angrezichatterbox! :)

**Review by andrewtavis — APPROVED** [review]

**Pull request merged**
