### PR TITLE
Fixes to installation icon size and menu control

### PR DESCRIPTION
**Pull request by MostafaMohamed2002**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

this is what it looks like after change the icon size and aligned it with text 
image

### Related issue

-   #153

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @MostafaMohamed2002 👋 For me the entire area still isn't clickable, which might not be clear :) Even if we click the gear icon it'd still be good to go to the keyboard settings, so it's a bit more of a refactor :)

**Comment by MostafaMohamed2002** [comment]
> Hey @MostafaMohamed2002 👋 For me the entire area still isn't clickable, which might not be clear :) Even if we click the gear icon it'd still be good to go to the keyboard settings, so it's a bit more of a refactor :)

so should i make the whole box clickable or just the gear icon ?

**Comment by andrewtavis** [comment]
The whole box :) Ideally the `Open keyboard settings` would also be underlined as it is in the designs, but we can do an issue for that later.

**Review by andrewtavis — APPROVED** [review]
Thanks so much for this, @MostafaMohamed2002! Great to have the installation screen up to these standards already 😊

**Pull request merged**
