### PR TITLE
Third party page

### PR DESCRIPTION
**Pull request by Linfye**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

This PR solves issue #60.

The current code has an issue where the "Third-party licenses" section is obscured by the background on the about page. To resolve this, I added `android:layout_marginBottom="30dp"` to create more space to avoid this. The other changes are similar to PR #72. 😊

### Related issue

-   #60

### CODE REVIEW

**Comment by andrewtavis** [comment]
@angrezichatterbox, do you want to give this a quick review, we bring it in, and then you can update #74 with what's needed to then merge that with the necessary changes for here?

**Comment by andrewtavis** [comment]
Thanks as well for the quick PR here, @Linfye! Really great 😊

**Review by angrezichatterbox — COMMENTED** [review]
The pull request looks great, @Linfye. Thank you for doing a quick PR for the issue. 

@andrewtavis, should the text "Custom Keyboard for Swift" be changed, or should it remain as is for now? Scribe-i18n has no strings for "Simple Keyboard," so should it be added from the front end as a string for now? Other than that, everything looks good in the pull request.

**Comment by andrewtavis** [comment]
Anything that's from Simple Keyboard can just be a hardcoded string :) 

We should do an issue soon to bring in all the strings from the designs and then have everything that we need going forward 😊

**Comment by angrezichatterbox** [comment]
> Anything that's from Simple Keyboard can just be a hardcoded string :)
> 
> We should do an issue soon to bring in all the strings from the designs and then have everything that we need going forward 😊

So @Linfye Could u replace the text references with Simple Keyboard whose reference can be seen [Simple Keyboard](https://github.com/SimpleMobileTools/Simple-Keyboard) as hardcoded strings.

**Comment by angrezichatterbox** [comment]
> Specifically I'm talking [scribe-org/Scribe-i18n#41](https://github.com/scribe-org/Scribe-i18n/issues/41), which should be done sooner rather than later. I could go through and list the strings that should be added, or even do this myself this weekend?

I had made a list of strings required earlier. I could confirm it and share with you the list.

**Comment by Linfye** [comment]
> > Anything that's from Simple Keyboard can just be a hardcoded string :)
> > We should do an issue soon to bring in all the strings from the designs and then have everything that we need going forward 😊
> 
> So @Linfye Could u replace the text references with Simple Keyboard whose reference can be seen [Simple Keyboard](https://github.com/SimpleMobileTools/Simple-Keyboard) as hardcoded strings.

You mean like [this](https://github.com/scribe-org/Scribe-Android/pull/75/commits/a3f3fe24047e9988d23db774541251070390db02)?

**Comment by angrezichatterbox** [comment]
> > > Anything that's from Simple Keyboard can just be a hardcoded string :)
> > > We should do an issue soon to bring in all the strings from the designs and then have everything that we need going forward 😊
> > 
> > 
> > So @Linfye Could u replace the text references with Simple Keyboard whose reference can be seen [Simple Keyboard](https://github.com/SimpleMobileTools/Simple-Keyboard) as hardcoded strings.
> 
> You mean like [this](https://github.com/scribe-org/Scribe-Android/pull/75/commits/a3f3fe24047e9988d23db774541251070390db02)?

Yes, it's good for now.

**Review by andrewtavis — APPROVED** [review]
Appreciate you picking up two issues so quickly, @Linfye! So amazing 🤩 We'll merge in the other open PR in the coming days, and then we'll be ready to work on other issues!

**Pull request merged**
