### PR TITLE
fix: Fix complex condition detekt errors

### PR DESCRIPTION
**Pull request by albendz**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description

Resolve complex condition errors for linting.

I tested this by running automated tests outside the project in my own scratch environment that made sure the before/after results of the boolean conditions were the same with and without my changes. I tried adding unit tests and started going really deep with mocking and hit some issues that didn't quite make sense when mocking in the MyKeyboardView constructor.

I'm not able to test the app on my device unfortunately. I've started a thread on Matrix for help.

## Testing code

```kotlin
    fun compareConditionFour(
        label: CharSequence?,
        mKeyBoardShiftState: Int?
    ): Boolean {
            var newLabel: CharSequence? = label
            if (newLabel != null && newLabel.isNotEmpty() && mKeyBoardShiftState!! > 3 && newLabel.length < 3 && Character.isLowerCase(newLabel[0])) {
                newLabel = newLabel.toString().toUpperCase()
            }

        val before = newLabel

        val after = label?.takeIf { it.length in 1..2 }?.let {
            if (mKeyBoardShiftState?.let { state -> state > 3 } == true) {
                label.toString().uppercase()
            } else {
                label
            }
        } ?: label

        return before == after
    }

   @Test
    fun compareConditionFour() {
        assertTrue(ComplexConditions.compareConditionFour(null, 1))
        assertTrue(ComplexConditions.compareConditionFour(null, 3))
        assertTrue(ComplexConditions.compareConditionFour(null, 4))

        assertTrue(ComplexConditions.compareConditionFour("ab", 1))
        assertTrue(ComplexConditions.compareConditionFour("ab", 3))
        assertTrue(ComplexConditions.compareConditionFour("ab", 4))

        assertTrue(ComplexConditions.compareConditionFour("", 1))
        assertTrue(ComplexConditions.compareConditionFour("", 3))
        assertTrue(ComplexConditions.compareConditionFour("", 4))

        assertTrue(ComplexConditions.compareConditionFour("null", 1))
        assertTrue(ComplexConditions.compareConditionFour("null", 3))
        assertTrue(ComplexConditions.compareConditionFour("null", 4))

        assertTrue(ComplexConditions.compareConditionFour("nul", 1))
        assertTrue(ComplexConditions.compareConditionFour("nul", 3))
        assertTrue(ComplexConditions.compareConditionFour("nul", 4))
    }

    fun compareConditionFive(
        mBuffer: Pair<Int, Int>?,
        mKeyboardChanged: Boolean,
        width: Int,
        length: Int
    ): Boolean {
        val before = if (mBuffer == null || mKeyboardChanged) {
            mBuffer == null || mKeyboardChanged && (mBuffer!!.first != width || mBuffer!!.second != length)
        } else false

        val after = if (mBuffer == null || mKeyboardChanged) mBuffer?.let { buffer -> buffer.first != width || buffer.second != length } != false else false

        return before == after
    }

    @Test
    fun testComplexConditionFive() {
        assertTrue(ComplexConditions.compareConditionFive(null, false, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive((0 to 0), false, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive((0 to 0), true, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive(null, true, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive((1 to 0), false, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive((1 to 0), true, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive((0 to 1), false, 0, 0))
        assertTrue(ComplexConditions.compareConditionFive((0 to 1), true, 0, 0))
    }

    fun compareConditionSix(
        code: Int
    ): Boolean {
        val before = code == 1 || code == 2 || code == 3 || code == 4 || code == 5
        val after = code in listOf(1, 2, 3, 4, 5)

        return before == after
    }

    @Test
    fun testComplexConditionSix() {
        assertTrue(ComplexConditions.compareConditionSix(0))
        assertTrue(ComplexConditions.compareConditionSix(1))
        assertTrue(ComplexConditions.compareConditionSix(2))
        assertTrue(ComplexConditions.compareConditionSix(3))
        assertTrue(ComplexConditions.compareConditionSix(4))
        assertTrue(ComplexConditions.compareConditionSix(5))
        assertTrue(ComplexConditions.compareConditionSix(6))
    }
```

### Related issue

-   #109

### CODE REVIEW

**Review by angrezichatterbox — APPROVED** [review]
Great PR @albendz. The changes look good to me. Thanks :)

**Comment by andrewtavis** [comment]
Could we get the merge conflicts resolved and then I'll bring this in? Thanks so much to you both!

**Comment by albendz** [comment]
I'll take a look at the merge conflicts

**Review by andrewtavis — APPROVED** [review]
Appreciate the help with the merge conflicts, @albendz! Thanks for all your support to the project 😊

**Pull request merged**
