### PR TITLE
Add MainActivityTest for Dark Mode Preference Handling

### PR DESCRIPTION
**Pull request by KesharwaniArpita**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Data/blob/main/CONTRIBUTING.md#testing)

---

### Description

This PR introduces a new test class, MainActivityTest, to verify the correct application of user dark mode preferences in the MainActivity. The tests utilize MockK to simulate shared preferences and verify that AppCompatDelegate switches modes correctly based on the user's settings.

Added MainActivityTest class in `app/src/test/kotlin/activities`.
- Created two test cases:
1. `testApplyUserDarkModePreference_darkModeEnabled()`: Verifies that dark mode is enabled when the dark_mode preference is set to true.
2. `testApplyUserDarkModePreference_darkModeDisabled()`: Verifies that dark mode is disabled when the dark_mode preference is set to false.

Test Details:

1. `testApplyUserDarkModePreference_darkModeEnabled()`:
- Sets `dark_mode` preference to true.
- Launches MainActivity and calls `applyUserDarkModePreference`.
- Asserts that `AppCompatDelegate` mode is set to `MODE_NIGHT_YES`.
2. `testApplyUserDarkModePreference_darkModeDisabled()`:
- Sets `dark_mode` preference to false.
- Launches MainActivity and calls `applyUserDarkModePreference`.
- Asserts that `AppCompatDelegate` mode is set to `MODE_NIGHT_NO`.

### Related issue

-   #197

### CODE REVIEW

**Comment by KesharwaniArpita** [comment]
Hi @albendz @andrewtavis I cannot figure out the reason for failing tests here.

**Comment by angrezichatterbox** [comment]
I will be only able to review it tomorrow or on Monday. As for the error it is because the MainActivityTest is not present in package be.scri.activities. It is currently not in any package.

**Comment by angrezichatterbox** [comment]
The detekt issues can be solved as I stated above. I am unsure about the other error that has popped up. I would have to look into it and figure it out. If you want to check it out I have found Roboelectric as a possible thing to check in case of this issue where we would be able to avoid mocking everything Android tells us to.

**Comment by MahmoudMabrok** [comment]
> The detekt issues can be solved as I stated above. I am unsure about the other error that has popped up. I would have to look into it and figure it out. If you want to check it out I have found Roboelectric as a possible thing to check in case of this issue where we would be able to avoid mocking everything Android tells us to.

yes Roboelectric is solution, but we should not start testing parts that are need platform classes implementation like Context. 

these parts might be involved in integration tests not unit tests.

**Comment by angrezichatterbox** [comment]
> > The detekt issues can be solved as I stated above. I am unsure about the other error that has popped up. I would have to look into it and figure it out. If you want to check it out I have found Roboelectric as a possible thing to check in case of this issue where we would be able to avoid mocking everything Android tells us to.
> 
> yes Roboelectric is solution, but we should not start testing parts that are need platform classes implementation like Context.
> 
> these parts might be involved in integration tests not unit tests.
> 
> i.e. Activity, Fragment, CustomView should not be unit tested, we should stick to test logic not UI staff.
> 
> for UI we can use Espresso framework.

Yes, it's an instrumentation test—I discovered that yesterday. We'll hold off on this until the Compose issues are merged to avoid making test changes later. Thanks, @MahmoudMabrok!

**Comment by angrezichatterbox** [comment]
I would be working on this now.

**Comment by andrewtavis** [comment]
Perfect, thanks @angrezichatterbox! Really appreciate it :)

**Comment by angrezichatterbox** [comment]
For now I have disabled connectedCoreDebugAndroidTest for Jacoco in the workflow. Should I add emulator support to the workflow to run the connectedCoreDebugAndroidTest which Jacobo has in workflow.

**Review by andrewtavis — APPROVED** [review]
Let's bring this in for now and we can make an issue detailing what'd be needed to add emulator support to the workflow to run connectedCoreDebugAndroidTest, @angrezichatterbox 😊 Would be good to bring this to a close :)

Thanks much for the contribution here, @KesharwaniArpita, and also for the support and closing it out, @angrezichatterbox!

**Pull request merged**
