### PR TITLE
Change Application identifier

### PR DESCRIPTION
**Pull request by angrezichatterbox**
### Description

The pull request changes the application identifier from org.scribe to be.scri. 

### Related issue
-   #42 

- #### Additional information
1. For some reason the old method of checking of whether it was a new user and telling the user to go to settings didn't seem to work so I had to make the check using the package name of those input picker additions. Should I revert that change. ?

### CODE REVIEW

**Comment by andrewtavis** [comment]
Hey @angrezichatterbox 👋

> For some reason the old method of checking of whether it was a new user and telling the user to go to settings didn't seem to work so I had to make the check using the package name of those input picker additions. Should I revert that change. ?

We actually discussed in the sync today, and we would prefer for the app to not force the user to install a keyboard. We'll direct them to install the keyboard on the installation page, and keyboard settings will be conditional on them being installed. It should be ok to revert that change so that the app opens without the tooltip telling the user to install the keyboard. Can you remove the code for that?

**Comment by angrezichatterbox** [comment]
> Hey @angrezichatterbox 👋
> 
> > For some reason the old method of checking of whether it was a new user and telling the user to go to settings didn't seem to work so I had to make the check using the package name of those input picker additions. Should I revert that change. ?
> 
> We actually discussed in the sync today, and we would prefer for the app to not force the user to install a keyboard. We'll direct them to install the keyboard on the installation page, and keyboard settings will be conditional on them being installed. It should be ok to revert that change so that the app opens without the tooltip telling the user to install the keyboard. Can you remove the code for that?

I have reverted the change.

**Comment by andrewtavis** [comment]
Checking it right now :) On build I'm getting the following error:

> Activity class {org.scribe.debug/be.scri.activities.SplashActivity.Orange} does not exist

Maybe there's a spot where it's still `org.scribe` in the code?

**Comment by angrezichatterbox** [comment]
> Checking it right now :) On build I'm getting the following error:
> 
> > Activity class {org.scribe.debug/be.scri.activities.SplashActivity.Orange} does not exist
> 
> Maybe there's a spot where it's still `org.scribe` in the code?

I have replaced it now in the latest commit to wherever I found org.scribe. I'm sorry that I didn't check again. the refractor of Android Studio does not change it everywhere. Could you try to invalidate the cache and rebuild it as  I am not able to replicate the same error.

**Comment by andrewtavis** [comment]
Sure, will do a little later today, @angrezichatterbox!

**Review by andrewtavis — APPROVED** [review]
I'm still getting the requirement to install a keyboard at the start, but it's all good for now.  We can make an issue for that specifically :)

Invalidating the cache did get rid of the error :) Thanks for this, @angrezichatterbox! 😊

**Pull request merged**
